export const ERROR_CODES = {
  E_TEMPLATE_INVALID: "E_TEMPLATE_INVALID",
  E_CRM_NO_MATCH: "E_CRM_NO_MATCH",
  E_PLATE_SIZE_MISSING: "E_PLATE_SIZE_MISSING",
  E_XML_INVALID: "E_XML_INVALID",
  E_OPTI_XML_TIMEOUT: "E_OPTI_XML_TIMEOUT",
  E_OSI_ACK_TIMEOUT: "E_OSI_ACK_TIMEOUT",
  E_OSI_ACK_FAILED: "E_OSI_ACK_FAILED",
  E_BACKING_THICKNESS_UNKNOWN: "E_BACKING_THICKNESS_UNKNOWN",
  E_TRIM_RULE_MISSING: "E_TRIM_RULE_MISSING",
  E_INVALID_GRAIN: "E_INVALID_GRAIN",
  E_EDGE_MAPPING_UNKNOWN: "E_EDGE_MAPPING_UNKNOWN",
  E_RETRY_LIMIT_REACHED: "E_RETRY_LIMIT_REACHED",
  E_OPERATOR_TRIGGER_REQUIRED: "E_OPERATOR_TRIGGER_REQUIRED",
  E_OPTI_MODE_A_RUNNER_MISSING: "E_OPTI_MODE_A_RUNNER_MISSING",
  E_OPTI_MODE_B_MACRO_MISSING: "E_OPTI_MODE_B_MACRO_MISSING",
  E_OPTI_RUNNER_FAILED: "E_OPTI_RUNNER_FAILED",
  E_PHONE_REQUIRED: "E_PHONE_REQUIRED",
  E_JOB_NOT_FOUND: "E_JOB_NOT_FOUND",
  E_JOB_NOT_IN_HOLD: "E_JOB_NOT_IN_HOLD",
  E_VALIDATION: "E_VALIDATION",
  E_UNKNOWN: "E_UNKNOWN",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const PERMANENT_ERRORS: ReadonlySet<string> = new Set([
  ERROR_CODES.E_TEMPLATE_INVALID,
  ERROR_CODES.E_CRM_NO_MATCH,
  ERROR_CODES.E_PLATE_SIZE_MISSING,
  ERROR_CODES.E_XML_INVALID,
]);

export const HOLD_ERROR_CODES: ReadonlySet<string> = new Set([
  ERROR_CODES.E_TEMPLATE_INVALID,
  ERROR_CODES.E_CRM_NO_MATCH,
  ERROR_CODES.E_PLATE_SIZE_MISSING,
  ERROR_CODES.E_OPERATOR_TRIGGER_REQUIRED,
  ERROR_CODES.E_BACKING_THICKNESS_UNKNOWN,
  ERROR_CODES.E_TRIM_RULE_MISSING,
]);
