DEFAULT_PAGINATION_SKIP = 0
DEFAULT_PAGINATION_LIMIT = 100
MAX_PAGINATION_LIMIT = 1000

PROMISE_STATUS_MIN_LENGTH = 3
PROMISE_STATUS_MAX_LENGTH = 20

__all__ = [
    "DEFAULT_PAGINATION_SKIP",
    "DEFAULT_PAGINATION_LIMIT",
    "MAX_PAGINATION_LIMIT",
    "PROMISE_STATUS_MIN_LENGTH",
    "PROMISE_STATUS_MAX_LENGTH",
]
