import type { CSSProperties } from "react";

export type OrderOptimizationThemeMode = "light" | "dark";

export const ORDER_OPTIMIZATION_THEME: Record<OrderOptimizationThemeMode, CSSProperties> = {
  light: {
    "--op-main-bg": "#F3F4F6",
    "--op-surface-bg": "#FFFFFF",
    "--op-border": "#D1D5DB",
    "--op-accent": "#0078D4",
    "--op-danger": "#EF4444",
    "--op-text": "#0F0F0F",
    "--op-muted": "#0F0F0F",
    "--op-index-bg": "#F3F4F6",
  } as CSSProperties,
  dark: {
    "--op-main-bg": "#0F0F0F",
    "--op-surface-bg": "#1E1E1E",
    "--op-border": "#333333",
    "--op-accent": "#38BDF8",
    "--op-danger": "#B91C1C",
    "--op-text": "#F3F4F6",
    "--op-muted": "#F3F4F6",
    "--op-index-bg": "#0F0F0F",
  } as CSSProperties,
};

export const orderOptimizationStyles = {
  panel: "flex min-h-[calc(100vh-132px)] w-full flex-col overflow-hidden border border-[var(--op-border)] bg-[var(--op-main-bg)] text-[var(--op-text)]",
  ribbonShell: "flex h-20 flex-col border-b border-[var(--op-border)] bg-[var(--op-surface-bg)]",
  titleBar: "flex h-9 items-center justify-between border-b border-[var(--op-border)] px-2",
  titleGroup: "flex items-center gap-2",
  logo: "flex h-5 w-5 items-center justify-center border border-[var(--op-accent)] bg-[var(--op-main-bg)] text-[10px] font-semibold text-[var(--op-accent)]",
  titleTextWrap: "flex items-center gap-2",
  title: "text-[12px] font-semibold leading-none",
  titleMeta: "text-[10px] leading-none text-[var(--op-muted)] opacity-80",
  windowControls: "flex items-center gap-1",
  windowButton: "flex h-5 w-6 items-center justify-center border border-[var(--op-border)] bg-[var(--op-surface-bg)] text-[var(--op-text)] hover:border-[var(--op-accent)] hover:text-[var(--op-accent)]",
  tabBar: "flex h-[calc(100%-36px)] items-end border-b border-[var(--op-border)] px-2",
  tabList: "flex h-11 items-end gap-0",
  tab: "relative flex h-11 min-w-[88px] items-center justify-center border-l border-r border-t border-transparent px-3 text-[11px] font-semibold text-[var(--op-text)]",
  activeTab: "border-[var(--op-border)] bg-[var(--op-main-bg)] text-[var(--op-accent)]",
  activeTabUnderline: "absolute bottom-0 left-0 right-0 h-0.5 bg-[var(--op-accent)]",
  minimizedBanner: "flex h-9 items-center border-b border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-[10px] font-semibold uppercase tracking-[0.04em] text-[var(--op-accent)]",
  metaStrip: "flex h-[65px] flex-nowrap items-center space-x-4 overflow-x-auto border-b border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2",
  metaBlock: "flex min-w-0 flex-col justify-center gap-1",
  metaLabel: "text-[10px] font-semibold uppercase leading-none tracking-[0.04em] text-[var(--op-text)] opacity-80",
  input: "h-8 rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-[12px] text-[var(--op-text)] outline-none placeholder:text-[var(--op-text)] placeholder:opacity-60 focus:border-[var(--op-accent)] focus:ring-0",
  inputDisabled: "h-8 rounded-none border border-[var(--op-border)] bg-[var(--op-main-bg)] px-2 text-[12px] text-[var(--op-text)] opacity-80 outline-none",
  monoInput: "h-8 rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-right text-[12px] text-[var(--op-text)] outline-none focus:border-[var(--op-accent)] focus:ring-0",
  gridShell: "flex flex-1 flex-col overflow-hidden bg-[var(--op-main-bg)]",
  gridNotice: "flex h-7 items-center justify-between border-b border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-[10px] font-semibold uppercase tracking-[0.04em]",
  gridFrame: "w-full flex-1 overflow-x-auto",
  gridHeaderRow: "grid border-b border-[var(--op-border)] bg-[var(--op-surface-bg)]",
  gridHeaderCell: "flex h-8 items-center border-r border-[var(--op-border)] px-2 text-[10px] font-semibold uppercase tracking-[0.04em]",
  gridViewport: "relative h-full min-h-[520px] overflow-auto",
  gridRow: "grid",
  indexCell: "flex items-center justify-between border-b border-r border-[var(--op-border)] bg-[var(--op-index-bg)] px-1 text-[11px]",
  cell: "flex items-center border-b border-r border-[var(--op-border)] bg-[var(--op-surface-bg)] px-1",
  partInput: "h-8 w-full rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-[12px] text-[var(--op-text)] outline-none focus:border-[var(--op-accent)] focus:ring-0",
  quantityInput: "h-8 w-full rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-1 text-center text-[12px] text-[var(--op-text)] outline-none focus:border-[var(--op-accent)] focus:ring-0",
  rotationButton: "flex h-8 w-8 items-center justify-center rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] text-[var(--op-text)] outline-none focus:border-[var(--op-accent)] hover:border-[var(--op-accent)] hover:text-[var(--op-accent)]",
  pvcButton: "flex h-[15px] w-[15px] items-center justify-center rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] text-[9px] font-semibold leading-none text-[var(--op-text)]",
  pvcActive: "border-[var(--op-accent)] bg-[var(--op-accent)] text-[#FFFFFF]",
  previewWrap: "flex h-[50px] w-[50px] items-center justify-center border border-[var(--op-border)] bg-[var(--op-main-bg)]",
  previewSvg: "h-[50px] w-[50px]",
  previewRect: "fill-none stroke-[var(--op-border)]",
  monoText: "font-mono",
  commandButton: "flex h-6 items-center justify-center rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-[10px] font-semibold uppercase tracking-[0.04em] text-[var(--op-text)] hover:border-[var(--op-accent)] hover:text-[var(--op-accent)]",
  dangerCommandButton: "border-[var(--op-danger)] text-[var(--op-danger)] hover:border-[var(--op-danger)] hover:text-[var(--op-danger)]",
  noticeDanger: "text-[var(--op-danger)]",
  noticeAccent: "text-[var(--op-accent)]",
} as const;
