import type { CSSProperties } from "react";

export type OrderOptimizationThemeMode = "light" | "dark";

export const ORDER_OPTIMIZATION_THEME: Record<OrderOptimizationThemeMode, CSSProperties> = {
  light: {
    "--op-main-bg": "#F0F0F0",
    "--op-surface-bg": "#FFFFFF",
    "--op-border": "#C6C6C6",
    "--op-accent": "#005A9E",
    "--op-danger": "#EF4444",
    "--op-text": "#0F0F0F",
    "--op-muted": "#0F0F0F",
    "--op-index-bg": "#F0F0F0",
  } as CSSProperties,
  dark: {
    "--op-main-bg": "#121212",
    "--op-surface-bg": "#1E1E1E",
    "--op-border": "#333333",
    "--op-accent": "#0078D4",
    "--op-danger": "#B91C1C",
    "--op-text": "#F3F4F6",
    "--op-muted": "#F3F4F6",
    "--op-index-bg": "#0F0F0F",
  } as CSSProperties,
};

export const orderOptimizationStyles = {
  panel: "flex min-h-[calc(100vh-132px)] w-full flex-col overflow-hidden border border-[var(--op-border)] bg-[var(--op-main-bg)] text-[var(--op-text)]",
  ribbonShell: "flex h-16 flex-col border-b border-[var(--op-border)] bg-[#252525]",
  titleBar: "flex h-16 items-center justify-between px-8",
  titleGroup: "flex items-center gap-3",
  logo: "text-5xl font-bold uppercase tracking-wide text-[var(--op-accent)]",
  titleTextWrap: "flex items-center gap-2",
  title: "text-[12px] font-semibold leading-none",
  titleMeta: "text-[10px] leading-none text-[var(--op-muted)] opacity-80",
  windowControls: "flex items-center gap-1",
  windowButton: "flex h-5 w-6 items-center justify-center border border-[var(--op-border)] bg-[var(--op-surface-bg)] text-[var(--op-text)] hover:border-[var(--op-accent)] hover:text-[var(--op-accent)]",
  tabBar: "hidden",
  tabList: "flex h-16 items-center gap-0",
  tab: "relative flex h-16 items-center justify-center px-6 text-sm font-medium text-[#e0e0e0] transition-colors hover:bg-[rgba(255,255,255,0.05)]",
  activeTab: "font-semibold text-[#00bcd4]",
  activeTabUnderline: "absolute bottom-0 left-0 right-0 h-[3px] bg-[#00bcd4] shadow-[0_0_8px_rgba(0,188,212,0.6)]",
  ribbonTools: "hidden",
  ribbonToolButton: "hidden",
  minimizedBanner: "flex h-9 items-center border-b border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-[10px] font-semibold uppercase tracking-[0.04em] text-[var(--op-accent)]",
  metaStrip: "flex h-[65px] flex-nowrap items-center space-x-6 overflow-x-auto border-b border-[var(--op-border)] bg-[var(--op-surface-bg)] px-3",
  metaBlock: "flex min-w-0 items-center gap-2",
  metaLabel: "text-[13px] font-semibold uppercase tracking-[0.04em] text-[var(--op-text)] opacity-75",
  input: "h-10 rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-[17px] text-[var(--op-text)] outline-none outline-offset-0 placeholder:text-[var(--op-text)] placeholder:opacity-60 focus:border-[var(--op-accent)] focus:ring-0",
  inputDisabled: "h-10 rounded-none border border-[var(--op-border)] bg-[var(--op-main-bg)] px-2 text-[17px] text-[var(--op-text)] opacity-80 outline-none outline-offset-0",
  monoInput: "h-full w-full rounded-none border-0 bg-transparent px-2 text-right text-[13px] text-[var(--op-text)] outline-none font-mono focus:bg-[rgba(0,188,212,0.05)]",
  messageStack: "grid gap-1 border-b border-[var(--op-border)] bg-[var(--op-main-bg)] px-2 py-1",
  messageBar: "border px-2 py-1 text-[11px]",
  messageDanger: "border-[var(--op-danger)] bg-[rgba(185,28,28,0.10)] text-[var(--op-danger)]",
  messageSuccess: "border-[var(--op-accent)] bg-[rgba(0,120,212,0.08)] text-[var(--op-accent)]",
  messageWarning: "border-[#D97706] bg-[rgba(217,119,6,0.10)] text-[#B45309]",
  detailStrip: "grid grid-cols-[repeat(auto-fit,minmax(250px,1fr))] gap-2 border-b border-[var(--op-border)] bg-[var(--op-main-bg)] px-2 py-2",
  detailCard: "flex min-h-[156px] flex-col gap-3 overflow-hidden border border-[var(--op-border)] bg-[var(--op-surface-bg)] p-2",
  detailCardTitle: "-mx-2 -mt-2 mb-1 border-b border-[var(--op-border)] bg-[var(--op-main-bg)] px-2 py-2 text-[15px] font-semibold uppercase tracking-[0.04em] text-[var(--op-accent)]",
  detailField: "grid gap-2 pt-1",
  detailFieldGrid: "grid grid-cols-2 gap-2",
  detailLabel: "text-[13px] font-semibold uppercase tracking-[0.04em] text-[var(--op-text)] opacity-75",
  inlineField: "flex h-10 items-center gap-2 border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2",
  metricGrid: "grid grid-cols-2 gap-2",
  metricItem: "flex flex-col gap-1 border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 py-1",
  metricValue: "text-[12px] font-semibold text-[var(--op-text)]",
  statusPill: "inline-flex h-6 items-center justify-center border border-[var(--op-accent)] bg-[rgba(0,120,212,0.10)] px-2 text-[10px] font-semibold uppercase tracking-[0.04em] text-[var(--op-accent)]",
  noticeLine: "flex flex-col gap-1 border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 py-1 text-[11px]",
  fileActionGrid: "grid grid-cols-2 gap-2",
  fileActionButton: "flex h-20 items-center justify-center gap-2 rounded-lg border-2 border-[var(--op-border)] bg-[var(--op-surface-bg)] px-4 py-3 text-[16px] font-semibold text-[var(--op-text)] hover:border-[var(--op-accent)] hover:text-[var(--op-accent)] hover:bg-[rgba(0,188,212,0.05)] disabled:cursor-not-allowed disabled:opacity-60",
  fileActionDanger: "border-[var(--op-danger)] text-[var(--op-danger)] hover:border-[var(--op-danger)] hover:text-[var(--op-danger)]",
  optimizationButton: "flex h-28 items-center justify-center gap-3 rounded-none border border-[#d32f2f] bg-[var(--op-surface-bg)] px-8 py-4 text-[40px] font-extrabold text-[#d32f2f] hover:bg-[#d32f2f] hover:text-white hover:border-[#d32f2f]",
  gridShell: "flex flex-1 flex-col overflow-hidden bg-[var(--op-main-bg)]",
  gridNotice: "flex h-7 items-center justify-between bg-[#252525] px-2 text-[10px] font-semibold uppercase tracking-[0.04em] text-[#00bcd4]",
  gridFrame: "w-full flex-1 overflow-x-auto border border-[#333]",
  gridHeaderRow: "grid bg-[var(--op-surface-bg)] border-b border-[#333]",
  gridHeaderCell: "flex h-6 items-center justify-center border-r border-[#333] px-2 text-[11px] font-medium text-[var(--op-text)]",
  gridViewport: "relative h-full min-h-[520px] overflow-auto",
  gridRow: "grid border-b border-[#333]",
  indexCell: "flex items-center justify-between bg-[var(--op-index-bg)] border-r border-[#333] px-2 text-[11px]",
  cell: "flex items-center bg-[var(--op-surface-bg)] border-r border-[#333]",
  partInput: "h-full w-full rounded-none border-0 bg-transparent px-2 text-[13px] text-[var(--op-text)] outline-none font-sans focus:bg-[rgba(0,188,212,0.05)]",
  quantityInput: "h-full w-full rounded-none border-0 bg-transparent px-2 text-center text-[13px] text-[var(--op-text)] outline-none font-sans focus:bg-[rgba(0,188,212,0.05)]",
  selectInput: "h-10 w-full rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-3 py-2 text-[16px] leading-6 text-[var(--op-text)] outline-none appearance-none font-sans focus:bg-[rgba(0,188,212,0.05)] focus:border-[var(--op-accent)]",
  rotationButton: "flex h-8 w-8 items-center justify-center rounded-none bg-transparent text-[var(--op-text)] outline-none hover:bg-[rgba(0,188,212,0.1)] hover:text-[#00bcd4]",
  pvcButton: "flex h-8 min-w-[42px] items-center justify-center rounded-none bg-transparent text-[11px] font-semibold text-[var(--op-text)] hover:bg-[rgba(0,188,212,0.1)]",
  pvcActive: "bg-[rgba(0,188,212,0.2)] text-[#00bcd4] font-bold",
  previewWrap: "flex h-[50px] w-[50px] items-center justify-center border border-[var(--op-border)] bg-[var(--op-main-bg)]",
  previewSvg: "h-[50px] w-[50px]",
  previewRect: "fill-none stroke-[var(--op-border)]",
  monoText: "font-mono",
  commandButton: "flex h-6 items-center justify-center rounded-none border border-[var(--op-border)] bg-[var(--op-surface-bg)] px-2 text-[10px] font-semibold uppercase tracking-[0.04em] text-[var(--op-text)] hover:border-[var(--op-accent)] hover:text-[var(--op-accent)]",
  dangerCommandButton: "border-[var(--op-danger)] text-[var(--op-danger)] hover:border-[var(--op-danger)] hover:text-[var(--op-danger)]",
  noticeDanger: "text-[var(--op-danger)]",
  noticeAccent: "text-[var(--op-accent)]",
  workspaceContent: "flex flex-1 overflow-hidden",
  quickAccessRail: "flex w-[40px] flex-col items-center gap-1 border-r border-[var(--op-border)] bg-[var(--op-surface-bg)] p-1",
  quickAccessBtn: "flex h-7 w-7 items-center justify-center rounded-none border border-[var(--op-border)] bg-[var(--op-main-bg)] text-[10px] font-semibold text-[var(--op-text)] hover:border-[var(--op-accent)] hover:text-[var(--op-accent)]",
} as const;
